name: Release

on:
  push:
    branches:
      - master

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ### Added
            - Feature 1
            - Feature 2
            ### Changed
            - Bugfix 1
            - Bugfix 2
          draft: false
          prerelease: false
